Compatibility update to support Joomla 4 and Mautic 4
mautic/mautic-joomla pull request #37
Opened 2023-04-14 14:22 UTC by LadySolveig

**What's changed**
* separated Mautic API Package - moved from plugin to own library
* create package with plugin and library
* changed API authorization method - supports only OAuth2
* change registered user add to mautic as contact instead of lead (Mautic 4)
* updated Readme
* moved Update.xml to main respository
**Additional**
* added tracking image for noscript 
* added embed tags shortcode from mautic instance
* updated regex for fixing bug with dynamic content emedding
**TODO**
* improve custom additional params in tracking script - not working at the moment
* change link in the update.xml to a release package and change also link to updateserver in mautic.xml to your needs
**IMPORTANT**
This version only supports Joomla 4.x.x and Mautic 4.x - no backward compatibility with previous versions

[MauticForJ4_2_0_0-rc.zip](https://github.com/mautic/mautic-joomla/files/11233726/MauticForJ4_2_0_0-rc.zip)

#35 #36

2023-05-16 11:45 UTC, RCheesley requested changes
Thanks so much @LadySolveig for making this PR and sorry it has taken me so long to get it reviewed. I have taken a first pass just looking at the text and spotted a few things. I will ask any of the core team to make a code review as well.

Findings from testing:

On install the flash message indicated that I should click to configure, taking me to administrator/index.php?option=com_plugins&filter_search=mautic - but this did not actually filter the list of plugins - I had to manually type 'Mautic' into the search filter (minor inconvenience!)

Enabling the plugin seems to work great - I already had it installed and it seems to have upgraded without any problems.

I see the update site pointing at the repo: http://mautic.github.io/mautic-joomla/updateserver.xml - I have enabled https for those resources so we can update that.

When I auth the plugin I see %Joomla% in the text - maybe we can make that a bit better for the user? Perhaps just removing the % would be a good start.

![screenshot-8080-mautic-mautic-oj3o901zusf ws-eu97 gitpod io-2023 05 16-12_36_38](https://github.com/mautic/mautic-joomla/assets/2930593/8c35829e-1a48-4b95-aeaa-f9b96470df24)

Finally, I struggled to get this to auth properly:

{"errors":[{"message":"The redirect URI provided does not match registered URI(s).","code":400,"type":"redirect_uri_mismatch"}]}

I checked that the URI in the API settings is the correct admin URL for the Joomla site so not sure what that is about - any thoughts?

2023-05-16 11:45 UTC, RCheesley commented on README.md
> +To embed Mautic Tags, insert this code snippet:
```suggestion
To embed the ability to append Mautic Tags to a contact on a page load, insert this code snippet:
```

2023-05-16 11:45 UTC, RCheesley commented on README.md
> +If you're forms are not embeded you can check the errors in the developer console of your browser. If you see an error like:
```suggestion
If your forms are not embedded you can check the errors in the developer console of your browser. If you see an error like:
```

2023-05-16 11:45 UTC, RCheesley commented on plg_system_mautic/README.md
> +Tracking option works right after you enable the plugin, insert Base URL and save the plugin. It loads a piece of javascript code to communicate with your Mautic instance.
```suggestion
The tracking option works right after you enable the plugin, insert Base URL and save the plugin. It loads a piece of javascript code to communicate with your Mautic instance.
```

2023-05-16 11:45 UTC, RCheesley commented on plg_system_mautic/README.md
> +If it doesn't work please check also your Mautic CORS configuration settings. If the CORS option is enabled in Mautic then the base url of the website where this plugin is running must be listed in v
```suggestion
If it doesn't work please check also your Mautic CORS configuration settings. If the CORS option is enabled in Mautic then the base URL of the website where this plugin is running must be listed in valid domains.
```

2023-05-16 11:45 UTC, RCheesley commented on plg_system_mautic/README.md
> +Tracking images for noscript option works right after you enable the plugin, insert Base URL and save the plugin. That means it will insert 1 px gif image loaded from your Mautic instance. You can ch
```suggestion
The tracking images for noscript option works right after you enable the plugin, insert the Base URL and save the plugin. That means it will insert 1 px gif image loaded from your Mautic instance. You can check HTML source code (CTRL + U) of your Joomla website to make sure the plugin works. You should be able to find something like this:
```

2023-05-16 11:45 UTC, RCheesley commented on plg_system_mautic/README.md
> +To embed Mautic Tags, insert this code snippet:
```suggestion
To embed the ability to append Mautic Tags to a contact on a page load, insert this code snippet:
```

2023-05-16 11:45 UTC, RCheesley commented on plg_system_mautic/README.md
> +2. At the right-hand side menu where Configuration is should appear new menu item 'API Credentials'. Hit it.
```suggestion
2. At the right-hand side menu where Configuration is displayed, there should appear new menu item 'API Credentials'. Click it.
```

2023-05-16 11:45 UTC, RCheesley commented on plg_system_mautic/README.md
> +[Current updateserver.xml](http://mautic.github.io/mautic-joomla/updateserver.xml)
```suggestion
[Current updateserver.xml](https://mautic.github.io/mautic-joomla/updateserver.xml)
```

2023-05-16 11:55 UTC, LadySolveig commented on plg_system_mautic/README.md
> +[Current updateserver.xml](http://mautic.github.io/mautic-joomla/updateserver.xml)
Thank you very much for code reviewing and your very clear failure descriptions. I will look into this the next view days.

2023-05-17 19:01 UTC, LadySolveig commented
@RCheesley thank you very much for your review. 
I commited your changes for the readme and fixed the broken search query from the flash install message.

The page you see when you first authenticate is created by Mautic and the "%" are not present in the current stable release. 
The descriptive name "Joomla" in your example is the name you give it on the Mautic API configuration page. In my case 'Test'.
![twig oauth mautic4](https://github.com/mautic/mautic-joomla/assets/64533137/efef907e-8c22-4a92-9d35-8cde87fb544c)
![oauth mautic4-j4-3](https://github.com/mautic/mautic-joomla/assets/64533137/018817db-1939-44a0-bedb-940773aba437)

I assume you tested with Mautic version 5. The authorization template has changed. Maybe the "%" comes from the view. I found the following lines in this context.
![twig oauth mautic5](https://github.com/mautic/mautic-joomla/assets/64533137/a6e2f68d-2de6-4fdc-a180-e45bc5050892)
![twig oauth mautic5-2](https://github.com/mautic/mautic-joomla/assets/64533137/adac8a53-0efe-4c54-bc40-c0b0ae469b23)

I installed the zip that I provided in this pull request and tested the API-Connection on the current Joomla Version 4.3.1 and current stable Mautic version 4.4.8. I'm sorry, I can't reproduce your issue with the connection.

That's my result with the default redirect path 'administrator'

![oauth mautic4-j4](https://github.com/mautic/mautic-joomla/assets/64533137/28523a3d-1134-4902-9287-9ef9f8c58d15)
![oauth mautic4-j4-2](https://github.com/mautic/mautic-joomla/assets/64533137/b9c070ff-291d-4397-98fa-d20bb4967cd1)

```

> #Date: 2023-05-17 18:12:26 UTC
> #Software: Joomla! 4.3.1 Stable [ Bora ] 2-May-2023 16:00 GMT
> 
> #Fields: datetime	priority clientip	category	message
> 2023-05-17T18:12:26+00:00	INFO 91.57.190.240	plg_system_mautic	Authorize method called.
> 2023-05-17T18:13:34+00:00	INFO 91.57.190.240	plg_system_mautic	Authorize method called.
> 2023-05-17T18:13:34+00:00	INFO 91.57.190.240	plg_system_mautic	authorize::accessTokenData: Joomla\Registry\Registry::__set_state(array(
>    'data' => 
>   (object) array(
>      'token' => 
>     (object) array(
>        'access_token' => 'M2E3NTFlN2MzNDZmZWQ5MTY3MWU4NTdlNzliMWYzNDk4OWE5ZGZmOGFhNDhlYTM2NDM4ZTJjY2Q1MjljYWY3OQ',
>        'expires' => 1684350814,
>        'token_type' => 'bearer',
>        'refresh_token' => 'NDZkODM1N2Y1NGE3YzBkMjliMDBiY2M1M2U0NzZkNDllNTVkNDY3ZmU3MGVlMjlhNzMzNDEzYWU1NTA5NzZlYQ',
>        'created' => '2023-05-17 18:13:34',
>     ),
>   ),
>    'initialized' => true,
>    'separator' => '.',

```

Can you please give me a hint on which versions you tested ?
Additionally, the Joomla log file named plg_system_mautic.php from folder administrator/logs would be very helpful.

2023-08-16 14:54 UTC, RCheesley commented
Hi there,

I went back to test this again - still getting the %Joomla Integration% so might be something that we need to look into for the 5.x branch - would you mind raising it as a bug?

I am still getting the auth error:

`{"errors":[{"message":"The redirect URI provided does not match registered URI(s).","code":400,"type":"redirect_uri_mismatch"}]}
`

I am testing with Mautic 5.x branch, and the git clone from the 4.3-dev branch of Joomla (before I was just using a regular 4.2.x Joomla install as I was testing on the dev area of my own website - this time I spun up a local instance for testing.

Here's the content of the log file:

```
#
#<?php die('Forbidden.'); ?>
#Date: 2023-08-16 14:48:04 UTC
#Software: Joomla! 4.3.4-rc2-dev Development [ Bora ] 15-August-2023 16:01 GMT

#Fields: datetime	priority clientip	category	message
2023-08-16T14:48:04+00:00	INFO 172.18.0.8	plg_system_mautic	Authorize method called.

```

In the Mautic side I have the redirect URI set to `https://mautic.ddev.site/administrator` and the Joomla side has the base URL set as `https://mautic.ddev.site` and the callback path as `administrator`.

Please let me know if I'm maybe setting something incorrectly!

2023-08-16 18:03 UTC, LadySolveig commented
@RCheesley nice to hear from you. I paused the project at the moment. Thank you for your infos. I will look into this the next 2 or 3 weeks give you feedback. I will also test with the new Joomla 5 version so we can go forward with this side project.

2024-03-15 23:57 UTC, RCheesley commented
Hey @LadySolveig I finally got around to testing this again but this time on my live site, and I've managed to auth properly! 🥳 

Works absolutely beautifully with the tracking!

Few things I found:

- Tagging works great, **but** when a tag is applied the page hit seems to be only from the homepage, which is a bit odd.
EG landed on https://ruthcheesley.co.uk/blog/marketing/top-tips-for-maximising-your-exhibition-experience-with-digital-marketing-and-social-media (marketing tag) and https://ruthcheesley.co.uk/blog/buddhism/when-things-go-wrong-tips-for-dealing-with-clients-who-have-had-a-bad-experience (buddhism tag) and the tag was correctly applied but the page hit URL in the contact profile is incorrect: 

![screenshot-m ruthcheesley co uk-2024 03 15-23_41_59](https://github.com/mautic/mautic-joomla/assets/2930593/77501357-e9d2-4bbd-850f-cfcf84960941)

Form embed works great:

![screenshot-ruthcheesley co uk-2024 03 15-23_46_18](https://github.com/mautic/mautic-joomla/assets/2930593/1af761c2-6cf7-40e8-b4c4-993572c723c7)

Gated video also working as expected:

![screenshot-ruthcheesley co uk-2024 03 15-23_48_37](https://github.com/mautic/mautic-joomla/assets/2930593/5a32c800-cfa0-4e43-a4a8-159bb97254f1)

I could not seem to get the DWC firing as I'd expect - it's just showing the default content despite matching on various fields (e.g. country for an anon visitor, or first name for a known visitor) but might be a separate issue.

Otherwise, awesome work!

2024-03-16 00:00 UTC, RCheesley requested changes
Forgot to leave a formal review, sorry!

2024-03-16 00:01 UTC, RCheesley commented
(PS it works great with Mautic 5.0.3 and Joomla 4.4.3 - haven't yet tested with Joomla 5 though!

2024-06-26 11:13 UTC, RCheesley commented
@LadySolveig do you think you might be able to get to fixing these small issues so we can release this? I'd love to get an updated Joomla plugin out there so we can start promoting it more heavily!

2024-06-26 14:53 UTC, LadySolveig commented
@RCheesley  I have to set up a new Mautic instance first, I am currently not so up to date and then I would like to test the compatibility with Joomla! 5 directly, but it could take another 3-4 weeks. 
I might be able to do it faster, but I don't want to promise that. Could you be patient with me until then?

2024-06-26 15:10 UTC, RCheesley commented
You can use Gitpod for that - https://gitpod.io/#https://github.com/mautic/mautic - or just do a git clone for the repo, and type ddev start if you use DDEV :) 

For sure can be patient - I already tested with Mautic 5.0.3 and Joomla 4.4.3 but haven't tried Joomla 5 just yet (waiting on a few plugins to be updated first!)

2024-06-26 19:02 UTC, LadySolveig commented
All your extensions that work in Joomla 4.4 should have no problems with Joomla 5.1 😉. You can also enable the compatibility Plugin If You have problems.

2025-01-22 09:21 UTC, LadySolveig commented
closed in favor to #38

2025-01-22 09:21 UTC, closed without merging

2025-04-03 17:57 UTC, miamicityman commented
I also confirm that tracking works fine, but have not gotten **Dynamic Content** to appear.

Per instructions:

- `{mautic type="content" slot="test-2025-a"}DEFAULT CONTENT HERE.{/mautic}`

in jom_content becomes ...

- `<div class="mautic-slot" data-slot-name="test-2025-a">DEFAULT CONTENT HERE.</div>`

in the front facing html, which I don't think is correct.